### ISSUE TITLE
On using the adapter

### ISSUE THREAD

**Issue by toncho11** [pkoning2/lk201emu#5]
Hi,

I managed to finally plug the adapter. In general it is working. 

1) So the F3 key (on the USB keyboard) switches between menu and writing modes? Right?
2) Can you type (do letters show) on the VT220 terminal without attaching it to a computer through serial? In my case I can not. I type, but nothing shows up.

I use the right "ENTER" for selecting options in the menu.  
Pressing too many keys on the keyboard lights up a red diode on the Adafruit controller.

**Comment by pkoning2** [comment]
Yes, F3 is the "Setup" function key on VT2xx and later terminals.  (Not on the Pro, though, it has a different function key layout.)  
I don't have a VT220, so I have to look in a manual to remind myself what it does.  The way I normally navigate the menu is using the cursor  keys, then Enter to do the selected action.
One of the options on the first setup screen is "On-line" which if you select and Enter should change to "Local".  That makes keyboard data go to the display directly, without any communication to any host.
The red light on the Arduino is the "Wait" LED (the fourth LED on the LK201).  I did it that way because I want all four to be visible, the other three are handled using the three PS keyboard LEDs.  See the documentation, it's mentioned in there.

**Comment by toncho11** [comment]
Thanks!!!

The terminal though is only in cyrillic letters when typing using English words in whatever language you choose. I guess they adapted the ROM, so that one can type in cyrillic, but in the end I do not see how to switch to English. It is because cyrillic was not built in, so they had to make un eagly hack. I think the only solution is an original ROM??

![IMG_20210801_211516](https://user-images.githubusercontent.com/1851997/127781588-d2b3a51f-984d-4f42-8da1-b3bdc15d043b.jpg)
![IMG_20210801_211617](https://user-images.githubusercontent.com/1851997/127781596-91197526-62f3-4805-b56c-1f29c02b0f5b.jpg)

**Comment by pkoning2** [comment]
Yes, looks like they replaced lower case letters by Cyrillic capital letters.  The original ROM would be the best solution.  Or use only upper case...

**Comment by toncho11** [comment]
Nice observation! It does work with capital letters in English. 
I still need both if I want to connect to a Linux terminal.
Some strategy can be developed!

I can add a code after your code in the adafruit controller:
- each capital English letter is converted to lower initially
- when F6 (for example) is pressed then it goes upper case in English
- when pressed again it goes to lower case in English again

**Comment by toncho11** [comment]
Actually I need another micro controller on the serial port output in order to do that, The display will always stay in English capital letters even if I manage to send both lower and capital letters to the connected computer. Or it could be a C program on the computer that translates to the correct English codes.

**Comment by toncho11** [comment]
You can update that:

Max3232EPE driver/receiver is also compatible as U3.

**Comment by pkoning2** [comment]
Thanks Toncho, I  updated the documentation to show that.
